package.path="dev/next-phase/?.lua;mod/common/media/lua/shared/?.lua;"..package.path
local C=require("CampaignPolicy")
local config={minGapHours=24,maxConcurrent=2,maxRetained=3}
local function req(id,hours,sites,active) return {caseId=id,createdHours=hours,survivalHours=hours,anchor={x=100,y=200},radius=(hours<96 and 250 or 500),siteIds=sites,activeIds=active or {},activeCount=#(active or {})} end
local state=C.new(); assert(C.validate(state))
assert(C.availability(state,config,req("case-1",0,{"a","b"})))
local first=req("case-1",0.5,{"a","b"}); local staged=assert(C.stage(state,config,first,{}))
assert(#state.records==0 and staged.records[1].anchor.x==100, "stage must not mutate input")
first.anchor.x=999; first.siteIds[1]="changed"; assert(staged.records[1].anchor.x==100 and staged.records[1].siteIds[1]=="a", "ledger must copy immutable creation facts")
assert(not C.availability(staged,config,req("case-2",24.49,{"c","d"})), "fractional gap edge must defer")
assert(C.availability(staged,config,req("case-2",24.5,{"c","d"})))
assert(not C.availability(staged,config,req("case-2",24.5,{"a","c"})), "retained site reuse must defer")
assert(not C.availability(staged,config,req("case-2",24.5,{"c","d"},{"foreign"})), "foreign active IDs reject")
assert(not C.availability(staged,config,req("case-2",24.5,{"c","d"},{"case-1","case-1"})), "concurrent cap is independent of completion")
local two=assert(C.stage(staged,config,req("case-2",24.5,{"c","d"}),{})); local three=assert(C.stage(two,config,req("case-3",48.5,{"e","f"}),{}))
assert(not C.availability(three,config,req("case-4",72,{"g","h"})), "retention cap defers instead of deleting")
assert(not C.stage(staged,config,req("bad",24.5,{"c","d"}),{ledger={}}), "reserved ledger key cannot evade budget accounting")
assert(not C.availability(state,{minGapHours=-1,maxConcurrent=2,maxRetained=3},req("bad",0,{"c","d"})))
assert(not C.availability(state,config,{caseId="bad"}), "malformed request rejects")
local cyclic=req("cycle",1,{"i","j"}); cyclic.self=cyclic; assert(not C.availability(state,config,cyclic), "cyclic request rejects")
assert(not C.config(setmetatable({minGapHours=1,maxConcurrent=1,maxRetained=1},{})), "metatable config rejects")
local wrong=req("radius",1,{"i","j"}); wrong.radius=1500; assert(not C.availability(state,config,wrong), "radius must match survival tier")
local extraAnchor=req("anchor",1,{"i","j"}); extraAnchor.anchor.extra=true; assert(not C.availability(state,config,extraAnchor), "anchor fields must be exact")
local unordered={schema=1,records={staged.records[1],{caseId="late",createdHours=0.25,survivalHours=0.25,anchor={x=1,y=1},radius=250,siteIds={"x","y"}}}}; assert(not C.validate(unordered), "history must remain ordered")
print("PASS CampaignPolicy: immutable anchors, gap/cap edges, retained sites, malformed input, and combined budget")
