local Session=require("ConspiracyFiles/Session")
local Content=require("ConspiracyFiles/Content")
local Placement=require("ConspiracyFiles/Placement")
local Scheduler=require("ConspiracyFiles/Scheduler")
local Bindings=require("ConspiracyFiles/Bindings")
local function target(session,id)
    local c=Placement.resolveCandidate(session.assignment(id))
    return {x=c.x,y=c.y,z=c.z,objectIndex=0,containerIndex=0,containerType=c.allowedContainerTypes[1],sprite="test-fixture"}
end
test("session rejects a sink failure without advancing domain or placement",function()
    local stored,fail
    local session=assert(Session.new(nil,37,function(v) if fail then error("sink fault") end; stored=v end))
    local before=session.snapshot(); fail=true
    local ok=session.command("discover",Content.ids.d1,"mock observation",Content.ids.relay)
    assertFalse(ok); assertDeepEqual(before,session.snapshot()); assertDeepEqual(before,stored)
    fail=false
    assertTrue(session.command("discover",Content.ids.d1,"mock observation",Content.ids.relay))
    assertEqual(2,#stored.domain.journal)
    local _,_,changed=session.command("discover",Content.ids.d1,"ignored duplicate",Content.ids.relay)
    assertFalse(changed); assertEqual(2,#stored.domain.journal)
end)
test("session placement intent and count-one commit round-trip as one root",function()
    local stored
    local s=assert(Session.new(nil,37,function(v) stored=v end))
    local id=Content.ids.d1
    assertTrue(s.bind(id,target(s,id))); assertTrue(s.intent(id))
    assertEqual("placing",stored.placement.assignments[id].status)
    assertEqual(nil,stored.domain.assetMaterialisation[id])
    assertFalse(s.placed(id,0)); assertTrue(s.placed(id,1))
    assertEqual("placed",stored.placement.assignments[id].status)
    assertEqual("materialised",stored.domain.assetMaterialisation[id])
    local restored=assert(Session.new(stored,999,function(v) stored=v end))
    assertDeepEqual(s.snapshot(),restored.snapshot())
end)
test("partial absence never activates fallback; explicit destruction does; conflicts stay sticky",function()
    local s=assert(Session.new(nil,37,function() end)); local id=Content.ids.d1
    assertTrue(s.bind(id,target(s,id))); assertTrue(s.intent(id)); assertTrue(s.placed(id,1))
    assertTrue(s.observe(id,0,false)); assertEqual(nil,s.snapshot().domain.entryOpportunityUsed)
    assertEqual("placed",s.assignment(id).status)
    assertTrue(s.observe(id,0,true)); assertEqual("fallback",s.snapshot().domain.entryOpportunityUsed)
    assertTrue(s.observe(id,2,false)); assertTrue(s.observe(id,1,false))
    assertEqual("conflict",s.assignment(id).availability)
    assertEqual("conflict",s.assignment(id).status)
end)
test("malformed legacy and oversized session roots are rejected without writes",function()
    local calls=0
    assertEqual(nil,Session.new({schemaVersion=1},1,function() calls=calls+1 end)); assertEqual(0,calls)
    local s=assert(Session.new(nil,37,function() end)); local bad=s.snapshot()
    bad.placement.assignments[Content.ids.d1].target={x=1,y=2,z=0,objectIndex=0,containerIndex=0,containerType="shelves",sprite="bad"}
    assertFalse(Session.validate(bad))
    bad=s.snapshot(); bad.extra=function() end; assertFalse(Session.validate(bad))
    bad=s.snapshot(); bad.placement.assignments[Content.ids.d1].target={x=10614,y=9604,z=0,objectIndex=0,containerIndex=0,containerType="shelves",sprite=string.rep("x",500001)}
    assertFalse(Session.validate(bad)); assertEqual(nil,Session.new(bad,1,function() calls=calls+1 end)); assertEqual(0,calls)
end)
test("arrival requires referenced exact binding and two identical square samples",function()
    local s=assert(Session.new(nil,37,function() end)); local sample=Bindings.newSampler()
    local square={x=10614,y=9604,z=0}
    assertEqual(nil,sample(s.view.snapshot(),square)); assertEqual(nil,sample(s.view.snapshot(),square))
    assertTrue(s.command("discover",Content.ids.d2,"mock police",Content.ids.police))
    assertEqual(nil,sample(s.view.snapshot(),square)); assertEqual(Content.ids.relay,sample(s.view.snapshot(),square))
    assertTrue(s.command("confirmLocation",Content.ids.relay))
    assertEqual(nil,sample(s.view.snapshot(),square))
    assertFalse(Bindings.match(Content.ids.relay,{x=10617,y=9604,z=0}))
    assertFalse(Bindings.match(Content.ids.relay,{x=10614,y=9604,z=1}))
    local reload=Bindings.newSampler(); assertEqual(nil,reload(s.view.snapshot(),square)); assertEqual(nil,reload(s.view.snapshot(),square))
end)
test("scheduler bounds records and deadline while failed subsystem leaves other jobs running",function()
    local now,steps,reports=0,0,0
    local q=Scheduler.new(function() return now end,function() reports=reports+1 end)
    q.enqueue("large","placement",function() steps=steps+1; now=now+0.5; return false end)
    assertEqual(4,q.step()); assertEqual(4,steps)
    assertFalse(q.enqueue("large","placement",function() end))
    q.failed("placement","one"); q.failed("placement","two"); q.failed("placement","three")
    assertTrue(q.isDisabled("placement")); assertEqual(2,reports)
    local ran=false; q.enqueue("arrival","arrival",function() ran=true; return true end); q.step(); assertTrue(ran)
end)
test("two-location contract retains all six documents and police-only context defers company name",function()
    assertEqual(2,#Content.thread.locationIds)
    assertEqual(Content.ids.relay,Content.assets[Content.ids.d4].placementLocationId)
    assertEqual(3,#Placement.assetsAt(Content.ids.relay))
    assertEqual(4,#Placement.assetsAt(Content.ids.police))
    assertFalse(string.find(Content.assets[Content.ids.d2].contextText,"Cumberland Signal Services",1,true)~=nil)
    assertFalse(string.find(Content.assets[Content.ids.d6].journalText,"Cumberland Signal Services",1,true)~=nil)
end)
