package.path="dev/next-phase/?.lua;"..package.path
local R=require("LocationReadiness")
assert(not R.new({"one","one"}) and not R.new({"one"}), "plan requires two distinct sites")
assert(not R.new({[1]="one",[3]="three"}) and not R.new({"one","two",extra=true}) and not R.new({string.rep("x",301),"two"}), "site array must be exactly two bounded IDs")
assert(not R.new(setmetatable({"one","two"},{})), "site array must not carry a metatable")
local plan=assert(R.new({"a","b"}))
assert(plan:observe({kind="metadata",siteId="a",storage="observed"}))
assert(not plan:authorized(), "metadata is not a container verification")
assert(plan:observe({kind="loaded",siteId="b",epoch=1}))
assert(plan:observe({kind="verification",siteId="b",epoch=1,result="positive"}))
assert(plan:observe({kind="loaded",siteId="a",epoch=1}))
assert(plan:observe({kind="verification",siteId="a",epoch=1,result="positive"}))
assert(plan:authorized(), "site event order must not matter")
assert(plan:observe({kind="unloaded",siteId="a"}) and not plan:authorized(), "unload invalidates readiness")
local before=plan:snapshot(); local status=before.sites.a.status
before.sites.a.status="ready"; assert(plan:snapshot().sites.a.status==status, "snapshot mutation must not affect reducer state")
assert(not plan:observe({kind="verification",siteId="a",epoch=1,result="positive"}), "verification while unloaded is invalid")
assert(plan:snapshot().sites.a.status==status, "invalid event must be atomic")
assert(plan:observe({kind="loaded",siteId="a",epoch=2}))
assert(not plan:observe({kind="verification",siteId="a",epoch=1,result="positive"}), "old load epoch must not revive readiness")
assert(plan:observe({kind="verification",siteId="a",epoch=2,result="positive"}) and plan:authorized())
assert(plan:observe({kind="verification",siteId="b",epoch=1,result="negative"}) and not plan:authorized(), "current absent storage is unsuitable")
assert(plan:observe({kind="verification",siteId="b",epoch=1,result="positive"}) and plan:authorized())
assert(plan:commit())
local frozen=plan:snapshot(); assert(not plan:observe({kind="unloaded",siteId="a"}) and not plan:commit(), "committed plan cannot reroll or relocate")
assert(plan:snapshot().sites.a.epoch==frozen.sites.a.epoch and plan:snapshot().committed, "committed freeze is atomic")
print("PASS LocationReadiness: metadata boundary, epochs, unload/reload, negative storage, event order, and committed freeze")
