-- Spoken "something is near" lines for the clue cue. First person, short,
-- plain. They say how the place feels, never what is there or what it means.
-- Written by Claude (owner, 2026-10-02). Keep every line free of names,
-- objects, theories and certainty.
return {
  "Something here doesn't sit right.",
  "Hold on. There's something around here.",
  "I should look around a bit more.",
  "My eyes keep going back to this spot.",
  "Wait. Something's off.",
  "I have a feeling I'm close to something.",
  "Hm. This place is hiding something.",
  "Something here is worth a second look.",
  "I can't shake the feeling there's more here.",
  "Slow down. Look properly.",
  "Something caught my eye just now.",
  "There's something nearby. I can almost feel it.",
  "That's odd. Let me look again.",
  "This corner feels different from the rest.",
  "I'm not alone with this place. Something's waiting here.",
  "Something about this doesn't add up.",
  "I should check around here.",
  "A strange feeling. Someone was here before me.",
  "Easy now. Take a good look around.",
  "I think I'm near something.",
  "Funny. This spot feels like it matters.",
  "Don't rush past this one.",
  "Something's been left here. I just know it.",
  "My gut says look closer.",
  "Whatever it is, it's close.",
  "There's more to this place than it shows.",
  "I keep feeling I'm missing something.",
  "Strange. Everything's too quiet here.",
  "I'm getting close. I can tell.",
  "Take your time. Something is here.",
  "Hm. That's not how I'd expect this to look.",
  "Something about this makes me stop.",
  "I'd swear someone wanted this left alone.",
  "Look around. Really look.",
  "This is the kind of place that keeps things.",
  "Something's been tucked away near here.",
  "That prickle on my neck again. Look closer.",
  "I'm onto something. Careful.",
  "A closer look wouldn't hurt.",
  "Something here is waiting to be noticed.",
  "I don't like this place, but I should look.",
  "This feels like the right spot to search.",
  "I almost walked right past it.",
  "My instincts say stay a moment.",
  "There's a reason I stopped here.",
  "I can't explain it, but something's here.",
  "Quiet now. Look carefully.",
  "Something doesn't belong. I can feel it.",
  "Let me not leave just yet.",
  "Somebody went to trouble here.",
  "That feeling again. I'm close.",
  "Better look around before I go.",
  "There's something here for those who look.",
  "I should poke around. Gently.",
  "It's not much, but something's different here.",
  "Something is just out of sight.",
  "Wait. Not so fast. Look.",
  "The air feels different around here.",
  "I think this place has a secret.",
  "Hmm, what's this feeling?",
  "I'd bet there's something to find.",
  "Careful. This could be something.",
  "Something is calling for a second glance.",
  "I'm sure I'm near something worth finding.",
  "Stop. Look around. Slowly.",
  "There's something here that wasn't put here by accident.",
  "I feel watched, and not by the dead. Look around.",
  "I'm standing right next to something. I know it.",
  "Don't trust the first look. Try another.",
  "My hands want to search this place.",
  "One more look around. Just to be sure.",
  "Something about the way this is laid out bothers me.",
  "It's here somewhere. I'm sure of it.",
  "I can't leave without checking.",
  "Odd. Things don't usually feel like this.",
  "Something's close. Don't waste it.",
  "I should search properly, not just glance.",
  "Whatever is here, it's near.",
  "Something here wants to be found.",
  "This place is holding its breath.",
  "Okay. Eyes open. There's something here.",
}
