return {
    Bootstrap = require("ConspiracyFiles/Bootstrap"),
    Content = require("ConspiracyFiles/Content"),
    ErrorBudget = require("ConspiracyFiles/ErrorBudget"),
    ArrivalAdapter = require("ConspiracyFiles/ArrivalAdapter"),
    Ids = require("ConspiracyFiles/Ids"),
    IntegrationRuntime = require("ConspiracyFiles/IntegrationRuntime"),
    ItemIdentityGateway = require("ConspiracyFiles/ItemIdentityGateway"),
    ItemPresentation = require("ConspiracyFiles/ItemPresentation"),
    ItemProjection = require("ConspiracyFiles/ItemProjection"),
    LifecycleAdapter = require("ConspiracyFiles/LifecycleAdapter"),
    LocationBindings = require("ConspiracyFiles/LocationBindings"),
    PersistenceAdapter = require("ConspiracyFiles/PersistenceAdapter"),
    PhysicalIdentity = require("ConspiracyFiles/PhysicalIdentity"),
    PhysicalToken = require("ConspiracyFiles/PhysicalToken"),
    PlacementAdapter = require("ConspiracyFiles/PlacementAdapter"),
    Presentation = require("ConspiracyFiles/Presentation"),
    PresentationRuntime = require("ConspiracyFiles/PresentationRuntime"),
    Renderer = require("ConspiracyFiles/Renderer"),
    Scheduler = require("ConspiracyFiles/Scheduler"),
    Journal = require("ConspiracyFiles/Journal"),
    ThreadState = require("ConspiracyFiles/ThreadState"),
    Validator = require("ConspiracyFiles/Validator"),
    WindowGeometry = require("ConspiracyFiles/WindowGeometry"),
    WorldRuntime = require("ConspiracyFiles/WorldRuntime")
}
