local K={};local MAX,OUT,WORK=64,64,512
local S={anonymousClue={"buildingId"},nameDocument={"sourceToken","name"},keySource={"sourceToken","keyToken","keyId"},keyDoorMatch={"keyToken","keyId","doorId","buildingId"}}
local function plain(t)return type(t)=="table" and not getmetatable(t)end
local function text(v)return type(v)=="string" and #v>0 and #v<=160 and not v:find("[%c]")end
local function kid(v)return type(v)=="number" and v==v and v~=math.huge and v~=-math.huge and v%1==0 and v>=0 end
local function cp(t)local n={};for k,v in pairs(t)do n[k]=type(v)=="table" and cp(v)or v end;return n end
local function fok(f)if not plain(f)or not S[f.kind]or not text(f.id)then return false end;local a={kind=true,id=true};for _,x in ipairs(S[f.kind])do a[x]=true end;for x in pairs(f)do if not a[x]then return false end end;for _,x in ipairs(S[f.kind])do if x=="keyId"then if not kid(f[x])then return false end elseif not text(f[x])then return false end end;return true end
local function sok(s)if not plain(s)or s.schema~=1 then return false end;for x in pairs(s)do if x~="schema"and not S[x]then return false end end;for k in pairs(S)do local b=s[k];if not plain(b)then return false end;local n=0;for id,f in pairs(b)do n=n+1;if n>MAX or not plain(f)or id~=f.id or f.kind~=k or not fok(f)then return false end end end;return true end
local function ids(b)local a={};for x in pairs(b)do a[#a+1]=x end;table.sort(a);return a end
local function eid(a)local n={};for i,v in ipairs(a)do n[i]=#v..":"..v end;return table.concat(n,";")end
function K.new()return {schema=1,anonymousClue={},nameDocument={},keySource={},keyDoorMatch={}}end
function K.observe(s,f)if not sok(s)then return nil,"invalid-state"end;if not fok(f)then return nil,"invalid-fact"end;local o=s[f.kind][f.id];if o then for x,v in pairs(o)do if f[x]~=v then return nil,"contradictory-id"end end;for x,v in pairs(f)do if o[x]~=v then return nil,"contradictory-id"end end;return cp(s),"duplicate"end;local n=0;for _ in pairs(s[f.kind])do n=n+1 end;if n>=MAX then return nil,"cap"end;local r=cp(s);r[f.kind][f.id]=cp(f);return r,"observed"end
function K.connections(s)if not sok(s)then return nil,"invalid-state"end;local src,mat,clu={}, {}, {};for _,id in ipairs(ids(s.keySource))do local f=s.keySource[id];src[f.sourceToken]=src[f.sourceToken]or{};table.insert(src[f.sourceToken],f)end;for _,id in ipairs(ids(s.keyDoorMatch))do local f=s.keyDoorMatch[id];local x=f.keyToken.."\0"..f.keyId;mat[x]=mat[x]or{};table.insert(mat[x],f)end;for _,id in ipairs(ids(s.anonymousClue))do local f=s.anonymousClue[id];clu[f.buildingId]=clu[f.buildingId]or{};table.insert(clu[f.buildingId],f)end;local r,w={},0;for _,id in ipairs(ids(s.nameDocument))do local d=s.nameDocument[id];for _,k in ipairs(src[d.sourceToken]or{})do for _,m in ipairs(mat[k.keyToken.."\0"..k.keyId]or{})do for _,c in ipairs(clu[m.buildingId]or{})do w=w+1;if w>WORK or #r>=OUT then return cp(r),"capped"end;r[#r+1]={id=eid({c.id,d.id,k.id,m.id}),clueId=c.id,documentId=d.id,keySourceId=k.id,matchId=m.id,name=d.name,statement="An observed key associated with the named document matches this building, suggesting a possible connection; it proves no person access, ownership, or authorship."}end end end end;return cp(r),"complete"end
return K
