#!/usr/bin/env python3
"""Generate the Fieldnote PDA's Lua geometry from the design package manifest.

    tools/fieldnote-test/build_fieldnote.py [path/to/manifest.json]

The design package's manifest.json is authoritative: every rectangle, colour,
text anchor, hitbox and pressed-state override comes from it. Nothing here is
transcribed by hand, so the Lua cannot drift from the design without this
script being re-run - and re-running it is the whole update path.

Output: mod/common/media/lua/shared/Fieldnote/Geometry.lua

Coordinate contract preserved exactly as the package states it: integer,
top-left origin, half-open rectangles as x, y, w, h; components draw in
ascending `order`; primitives draw in listed order. Palette is emitted as
{r, g, b, a} and the RENDERER adapts the order to each game call, because the
game's own signatures differ (drawRect takes alpha first, drawText takes it
last - both verified against the installed Build 42.20 Lua).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DEFAULT_MANIFEST = os.path.join(HERE, "design", "manifest.json")
OUT = os.path.join(REPO, "mod", "common", "media", "lua", "shared", "Fieldnote", "Geometry.lua")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MANIFEST
    with open(path) as f:
        m = json.load(f)
    assert m.get("schema_version") == 1, "unexpected manifest schema"

    dev = m["device"]
    lcd = m["lcd"]
    out = []
    w = out.append
    w("-- GENERATED by tools/fieldnote-test/build_fieldnote.py from the design")
    w("-- package's manifest.json. Do not edit by hand; edit the manifest and re-run.")
    w("--")
    w("-- Integer, top-left origin, half-open rectangles as {x, y, w, h}. Components")
    w("-- draw in ascending order; primitives in listed order. Colours are {r,g,b,a}")
    w("-- in [0,1]; the renderer reorders per game call.")
    w("local M={}")
    w("M.device={w=%d,h=%d}" % (dev["width"], dev["height"]))
    r = lcd["rect"]
    w("M.lcd={x=%d,y=%d,w=%d,h=%d}" % tuple(r))
    w("M.showWear=%s" % ("true" if m["default_visibility"].get("wear") else "false"))

    w("M.palette={")
    for name, c in m["palette"].items():
        rgba = c["rgba"]
        w("  %s={%.6f,%.6f,%.6f,%.6f},  -- %s" % (name, rgba[0], rgba[1], rgba[2], rgba[3], c["hex"]))
    w("}")

    comps = sorted(m["components"], key=lambda c: c["order"])
    w("M.components={")
    for c in comps:
        b = c["bounds"]
        w("  {id=%s,order=%d,role=%s,optional=%s,x=%d,y=%d,w=%d,h=%d," % (
            lua_str(c["id"]), c["order"], lua_str(c["role"]),
            "true" if c["optional"] else "false", b[0], b[1], b[2], b[3]))
        so = c.get("state_overrides")
        if so:
            w("   overrides={")
            for state, table in so.items():
                items = ",".join("[%s]=%s" % (lua_str(k), lua_str(v)) for k, v in table.items())
                w("     %s={%s}," % (state, items))
            w("   },")
        w("   primitives={")
        for p in c["primitives"]:
            assert p.get("alpha", 1) == 1 and p.get("border_thickness", 0) == 0, p["id"]
            if p["type"] == "rect":
                x, y, pw, ph = p["rect"]
                assert pw > 0 and ph > 0, p["id"]
                extra = ""
                if "pressed_color" in p:
                    extra = ",pressed=%s" % lua_str(p["pressed_color"])
                w("     {id=%s,kind=\"rect\",x=%d,y=%d,w=%d,h=%d,color=%s%s}," % (
                    lua_str(p["id"]), x, y, pw, ph, lua_str(p["color"]), extra))
            elif p["type"] == "text":
                w("     {id=%s,kind=\"text\",x=%d,baseline=%d,text=%s,align=%s,size=%d,font=%s,weight=%s,color=%s}," % (
                    lua_str(p["id"]), p["x"], p["baseline_y"], lua_str(p["text"]),
                    lua_str(p["align"]), p["size_px"], lua_str(p["font_category"]),
                    lua_str(p["weight"]), lua_str(p["color"])))
            else:
                raise SystemExit("unknown primitive type " + p["type"])
        w("   },")
        w("  },")
    w("}")

    w("M.controls={")
    for ctl in m["controls"]:
        hb = ctl["hitbox"]
        w("  {id=%s,x=%d,y=%d,w=%d,h=%d,action=%s}," % (
            lua_str(ctl["id"]), hb[0], hb[1], hb[2], hb[3], lua_str(ctl["action"])))
    w("}")
    w("return M")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    prims = sum(len(c["primitives"]) for c in comps)
    print("wrote %s: %d components, %d primitives, %d controls" % (
        os.path.relpath(OUT, HERE), len(comps), prims, len(m["controls"])))


if __name__ == "__main__":
    main()
