-- Generates Generated/Baseline.lua: the fingerprints and the held-back ids of the dependency version we shipped against.
-- Ids only (the dependency's ignored-entries.txt is a list of file names; no note file is read).
-- Usage: lua5.1 tools/ofinterest/gen_baseline.lua [--check]
package.path="mod-ofinterest/common/media/lua/shared/?.lua;"..package.path
local Cat=require("OIShared/NoteCatalogue")
local tables=require("OIShared/Generated/NoteTables")
local contract=require("OIShared/Generated/Contract")
local home=os.getenv("HOME")
local path=home.."/.steam/debian-installation/steamapps/workshop/content/108600/3796373365/mods/ItIsOfInterestToMe/42/media/lua/shared/ItIsOfInterestToMe/Content/ignored-entries.txt"
local f=assert(io.open(path,"r"))
local ignored={}
for line in f:lines() do
    local e=line:gsub("#.*$",""):gsub("%s",""):gsub("\r","")
    if e~="" then
        local pool,num=e:match("^([%w]+)/(%d+)%.txt$")
        if pool=="Note" then ignored["Note/"..num]=true
        elseif pool=="Letters" then error("unexpected "..e) end
        local cat,n2=e:match("^Letters/(%w+)/(%d+)%.txt$")
        if cat then ignored["Letter/"..cat.."/"..n2]=true end
    end
end
f:close()
local ids,dropped,counts={}, {}, {}
for _,p in ipairs(contract.pools) do counts[p]=0 end
for id in pairs(tables) do
    if ignored[id] then dropped[#dropped+1]=id
    else
        ids[#ids+1]=id
        local cat=id:match("^Letter/(%w+)/") or "Note"
        counts[cat]=counts[cat]+1
    end
end
table.sort(ids); table.sort(dropped)
local poolCount={}
for p,n in pairs(counts) do poolCount[#poolCount+1]=p.."="..n end
table.sort(poolCount)
local lines={}
for _,id in ipairs(ids) do lines[#lines+1]=id end
for _,s in ipairs(poolCount) do lines[#lines+1]="#"..s end
local out={"-- GENERATED by tools/ofinterest/gen_baseline.lua. Do not edit. The dependency version we shipped against:",
 "-- fingerprints of the table and of the live id list, the entry count and the ids the dependency itself holds back.",
 "return {",
 string.format('    static = "%s",', Cat.staticFingerprint(tables)),
 string.format('    dynamic = "%s",', Cat.hashLines(lines)),
 string.format("    entries = %d,", #ids),
 "    held = {"..(function() local t={} for _,d in ipairs(dropped) do t[#t+1]='"'..d..'"' end return table.concat(t,",") end)().."},",
 "}",""}
local text=table.concat(out,"\n")
local target="mod-ofinterest/common/media/lua/shared/OIShared/Generated/Baseline.lua"
if arg and arg[1]=="--check" then
    local g=io.open(target,"r"); local cur=g and g:read("*a"); if g then g:close() end
    print("baseline: "..(cur==text and "identical" or "DIFFERS")); os.exit(cur==text and 0 or 1)
end
local g=assert(io.open(target,"w")); g:write(text); g:close(); print("wrote "..target.." entries="..#ids.." held="..#dropped)
