#!/usr/bin/env python3
"""Generates mod-ofinterest/.../Generated/Contract.lua from the dependency's CODE (never its note files).

Usage: tools/ofinterest/gen_contract.py [--check] [DEPENDENCY_LUA_DIR]
DEPENDENCY_LUA_DIR defaults to the Steam Workshop copy of "It is of interest to me!" (3796373365).
--check: exit 1 when the shipped Contract.lua differs from what the dependency's code gives now.
Reads only .lua files: function names of ReadableItemRegistry, the modData key names, the world tracker
name, the pool names, the place-category list. Output is deterministic (sorted, no dates).
"""
import os, re, sys, glob

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "mod-ofinterest", "common", "media", "lua",
                   "shared", "OIShared", "Generated", "Contract.lua")
DEFAULT = os.path.expanduser("~/.steam/debian-installation/steamapps/workshop/content/108600/3796373365/mods/"
                             "ItIsOfInterestToMe/42/media/lua")
# What WE rely on (a dependency may have more; extra functions/keys are not a drift).
NEED_FUNCTIONS = ["getOrAssignText", "isRegistered", "open", "resolveTextById"]
NEED_KEYS = ["iioitmLetterCategory", "iioitmLocation", "iioitmLocationBaked", "iioitmTextId"]
PROBED_KEYS = ["iioitmTextId"]   # what getOrAssignText itself writes: checked at run time by a scratch probe
# Our 13 place codes (docs/design/OF_INTEREST_CODES.md): code -> category NAME.
PLACES = ["Hospital", "PoliceStation", "Prison", "Military", "Farm", "Church", "School", "Factory",
          "GasStation", "Laboratory", "Library", "Warehouse", "Restaurant"]

def lua_files(root):
    return sorted(glob.glob(os.path.join(root, "**", "*.lua"), recursive=True))

def generate(root):
    src = {p: open(p, encoding="utf-8").read() for p in lua_files(root)}
    allsrc = "\n".join(src.values())
    reg = next(v for p, v in src.items() if p.endswith("ReadableItemRegistry.lua"))
    funcs = set(re.findall(r"^function ReadableItemRegistry\.(\w+)\s*\(", reg, re.M))
    for f in NEED_FUNCTIONS:
        assert f in funcs, "dependency lost ReadableItemRegistry." + f
    for k in NEED_KEYS:
        assert re.search(r"\b" + k + r"\b", allsrc), "dependency no longer mentions " + k
    tr = sorted(set(re.findall(r'getOrCreate\("(\w+_UsedText)"\)', reg)))
    assert len(tr) == 1, "tracker name not unique: %r" % tr
    letters = next(v for p, v in src.items() if p.endswith("LetterContent.lua"))
    block = re.search(r"local CATEGORIES = \{(.*?)\}", letters, re.S).group(1)
    pools = sorted(["Note"] + re.findall(r'"(\w+)"', block))
    cat = next(v for p, v in src.items() if p.endswith("LocationCategory.lua"))
    cblock = re.search(r"KNOWN_CATEGORIES = \{(.*?)\}", cat, re.S).group(1)
    cats = re.findall(r'"(\w+)"', cblock)
    assert cats[:len(PLACES)] == PLACES, "place list no longer starts with our 13 codes"
    q = lambda l: "{" + ",".join('"%s"' % x for x in l) + "}"
    out = ["-- GENERATED by tools/ofinterest/gen_contract.py from the dependency's code (no note files). Do not edit.",
           "-- The contract OIShared/DriftGate checks the live dependency against. Names and shapes only.",
           "return {",
           "    version = 1,",
           "    functions = " + q(NEED_FUNCTIONS) + ",",
           "    keys = " + q(NEED_KEYS) + ",",
           "    probedKeys = " + q(PROBED_KEYS) + ",",
           '    tracker = { name = "%s", shape = "pool>id>true" },' % tr[0],
           "    pools = " + q(pools) + ",",
           '    idPattern = "^(%d+)%.txt$",',
           "    categories = " + q(cats) + ",",
           "    places = " + q(PLACES) + ",",
           "}", ""]
    return "\n".join(out)

if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = args[0] if args else DEFAULT
    text = generate(root)
    out = os.path.normpath(OUT)
    if "--check" in sys.argv:
        same = os.path.exists(out) and open(out, encoding="utf-8").read() == text
        print("contract: " + ("identical" if same else "DIFFERS"))
        sys.exit(0 if same else 1)
    open(out, "w", encoding="utf-8").write(text)
    print("wrote", out)
