-- DERIVED FILE - do not edit by hand. The No Help clue list (Manifest.clues).
--   lua5.1 tools/nohelp_content/convert.lua
-- from content/nohelp/accepted/*.json; authoring fields live in the sidecars
-- (content/nohelp/accepted/sidecar/). Writer and engineer material: the owner
-- plays blind and does not read this file.
return {clues={
-- T0001
{id="t0001-01",kind="set",pieces={"Map","KeyRing"},where={{place="police",spot="mailbox",lean="containment",rival="agricultural"}},title="The route stops at the barrier",body="The map's pencil road ends at a barrier mark. A keyring is tied across the fold; its blank tag is polished where a number was rubbed away."},
{id="t0001-02",kind="set",pieces={"Bucket","WaterBottle"},where={{place="police",spot="mailbox",lean="agricultural",rival="containment"}},title="The bottle kept the wrong color",body="A green ring stains the bottle's inner neck. The bucket beside it is dry, though its handle is wet and smells faintly of crushed leaves."},
-- T0002
{id="t0002-01",kind="set",pieces={"FirstAidKit","Bandage"},where={{place="hospital",spot="corpse",lean="containment",rival="agricultural",outfit="medical"}},title="The sealed kit on the medical coat",body="The kit's seal is unbroken. A bandage has been folded around its handle, still clean, with a patient wrist label tied through the fold and no name on it."},
{id="t0002-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="hospital",spot="corpse",lean="agricultural",rival="containment",outfit="medical"}},title="The bottle with a leaf-shaped tide",body="A brown tide line circles the bottle; the notebook beside it has one page stuck to the cap. When it lifts, a pressed leaf outline remains on the paper."},
-- T0003
{id="t0003-01",kind="set",pieces={"Map","KeyRing"},where={{place="farm",spot="ground",lean="containment",rival="agricultural"}},title="The key past the closure bar",body="The map shows a farm track ending at a thick road-closure bar. The keyring lies beyond it, tied to a tag stamped “county return.” Beside the bar, “all clear” is checked although the road is still crossed out."},
{id="t0003-02",kind="set",pieces={"SeedBag","HandShovel"},where={{place="farm",spot="ground",lean="agricultural",rival="containment"}},title="The seed bag holds a narrow trench",body="The seed bag is folded shut around the shovel handle. A straight line of dark soil runs from the blade to the bag's seam, but the shovel has no soil on its grip."},
-- T0004
{id="t0004-01",kind="set",pieces={"Map","Lunchbox"},where={{place="checkpoint",spot="vehicle",lean="containment",rival="agricultural"}},title="The lunch packed for the closed lane",body="The lunchbox is wedged beneath the map's fold. The route line passes the checkpoint and stops; a spoon has been laid across the road home."},
{id="t0004-02",kind="set",pieces={"Bucket","Fertilizer"},where={{place="checkpoint",spot="vehicle",lean="agricultural",rival="containment"}},title="The powder gathered in the bucket seam",body="Pale granules cling inside the bucket's rim. The fertilizer sack beside it is dry and carefully folded, with its open corner tucked under the seat."},
-- T0005
{id="t0005-01",kind="set",pieces={"Briefcase","Screwdriver"},where={{place="office",spot="furniture",lean="containment",rival="agricultural"}},title="The briefcase with an intact lock",body="The screwdriver lies inside the open briefcase. Its lock is intact, but the metal around the keyhole is bright from repeated turning; a loose key sits in the lining."},
{id="t0005-02",kind="set",pieces={"SeedBag","Fertilizer"},where={{place="office",spot="furniture",lean="agricultural",rival="containment"}},title="The seed packet tucked in the fertilizer fold",body="A seed packet is tucked into the fertilizer sack's stitched fold. Its planting diagram is intact; the small panel for mixing instructions has been cut out cleanly."},
-- T0006
{id="t0006-01",kind="set",pieces={"Map","Postcard"},where={{place="bookstore",spot="mailbox",lean="containment",rival="agricultural"}},title="The postcard addressed to a crossed street",body="The postcard is stamped and addressed, but the map beneath it ends at a street crossed out in pencil. The message stops after, “We were told to wait by—”."},
{id="t0006-02",kind="set",pieces={"Newspaper","Notebook"},where={{place="bookstore",spot="mailbox",lean="agricultural",rival="containment"}},title="The garden column with no matching season",body="A newspaper gardening column is folded around a notebook sketch of three crop rows. The drawing has a water line but no planting date; the column is for winter."},
-- T0007
{id="t0007-01",kind="set",pieces={"Clipboard","KeyRing"},where={{place="transmission",spot="vehicle",lean="containment",rival="agricultural"}},title="The keyring clipped over the empty page",body="The clipboard is closed around a keyring. One key leaves a clean outline in the dust, while the page beneath the clip has torn away at the holes."},
{id="t0007-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="transmission",spot="vehicle",lean="agricultural",rival="containment"}},title="The rain sketch runs into the bottle ring",body="The notebook shows rain crossing a set of crop rows. A water bottle rests on the open page; its dry ring circles the word “downhill,” written once and then erased."},
-- T0008
{id="t0008-01",kind="set",pieces={"Lunchbox","KeyRing"},where={{place="warehouse",spot="ground",lean="containment",rival="agricultural"}},title="The keys stayed outside the marked floor",body="The keyring is wrapped in the lunchbox's cloth lining. A chalk boundary crosses the lid; the ring is on the clean side and the meal on the dusty one."},
{id="t0008-02",kind="set",pieces={"Bucket","Notebook"},where={{place="warehouse",spot="ground",lean="agricultural",rival="containment"}},title="The trial strip curled after spraying",body="The notebook rests across the bucket. Its page labels two strips “control — standing” and “trial spray — curled by noon.” The next line reads “mix still active after valve shut.”"},
-- T0009
{id="t0009-01",kind="set",pieces={"Newspaper","RubberBand"},where={{place="government",spot="furniture",lean="containment",rival="agricultural"}},title="The headline held open over its correction",body="A rubber band keeps the newspaper open, but its fold covers the correction column. The headline is still visible; the folded page has split along the correction's first sentence."},
{id="t0009-02",kind="set",pieces={"GardeningSprayEmpty","Notebook"},where={{place="government",spot="furniture",lean="agricultural",rival="containment"}},title="The sprayer left its outline on the page",body="The empty garden sprayer has left a clean circle on the notebook beneath it. A dried green line runs from the nozzle to a sketch of crop rows."},
-- T0010
{id="t0010-01",kind="written",pieces={"idcard"},where={{place="farm",spot="corpse",lean="agricultural",rival="containment",outfit="farm"}},person="person-a",title="Temporary field access card",body="Field plots: weekly soil checks. Road access may close at short notice. Reverse: “Keep the old mare in the dry stall tonight.”"},
{id="t0010-02",kind="set",pieces={"Map","HandShovel"},where={{place="farm",spot="corpse",lean="agricultural",rival="containment",outfit="farm"}},person="person-a",title="The row that ends at the road",body="The map's crop row reaches the road and stops at a thumb-smudged mark. Soil fills the shovel socket but not the blade; its grip is clean."},
-- T0011
{id="t0011-01",kind="written",pieces={"idcard"},where={{place="office",spot="mailbox",lean="containment",rival="agricultural"}},person="person-b",title="County message runner card",body="Delivery: office to road crews. Return copy expected when access resumes. Reverse: “Please bring the chipped blue cup back; it was my sister's.”"},
{id="t0011-02",kind="set",pieces={"Clipboard","KeyRing"},where={{place="office",spot="mailbox",lean="containment",rival="agricultural"}},person="person-b",title="The clipboard held the only spare",body="A keyring is fastened beneath the clipboard clip. Its tag is worn smooth; the page above it has two pencil holes and no writing."},
-- T0012
{id="t0012-01",kind="written",pieces={"businesscard"},where={{place="checkpoint",spot="vehicle",lean="containment",rival="agricultural"}},person="person-c",title="Courier card with a late return",body="Transfer window: after road access ends. Return copy to sender. Reverse: “Bread for Mother, no crust if it is still warm.”"},
{id="t0012-02",kind="set",pieces={"Map","KeyRing"},where={{place="checkpoint",spot="vehicle",lean="agricultural",rival="containment"}},person="person-c",title="The key marked for the last spray run",body="The map routes past a checkpoint to the trial plots. A key tag says “sprayer pump.” In the margin, “wind turned at ten; east beans scorched by noon” is underlined twice."},
-- T0013
{id="t0013-01",kind="set",pieces={"Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The lap with no return mark",body="The map's route ends at a chalk line. A keyring rests across the fold back toward the starting point; its tag has no place name.",anchor={map="IrvingtonStashMap1",mark=1}},
{id="t0013-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The bottle's ring crosses a row sketch",body="A clear ring dries across the notebook's crop-row drawing. The bottle cap is clean; the page beneath it is stained only where the drawn rows meet.",anchor={map="IrvingtonStashMap1",note=1}},
{id="t0013-03",kind="written",pieces={"dispatch"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Dispatch copy with an unfinished return",body="“Track access ends at the barrier. Keep the west lane clear for the last vehicle.” The receiving line is blank; on the back, someone asks for a green scarf to be saved.",anchor={map="IrvingtonStashMap1",note=2}},
{id="t0013-04",kind="written",pieces={"notepad"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The row count continues past the page",body="The note lists three crop rows and a water check, then continues onto the cover. “Bring the small boots home” is written below the last line.",anchor={map="IrvingtonStashMap1",note=3}},
-- T0014
{id="t0014-01",kind="set",pieces={"Screwdriver","RubberBand"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The tire offer marked on a tool handle",body="A rubber band holds a service slip to the screwdriver. Four circles are drawn beside one wheel sketch; only the outer groove is filled with dark dust.",anchor={print="AmericanTire"}},
{id="t0014-02",kind="written",pieces={"receipt"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The fourth tire omitted from the return",body="The receipt charges four tires to the county road crew, but lists only three serial numbers. Beside the blank fourth line, someone wrote “keep off public return until clearance review.” Reverse: “Save the smoothest for the child's bicycle.”",anchor={print="AmericanTire"}},
-- T0015
{id="t0015-01",kind="set",pieces={"Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The key points past the marked road",body="The map is folded toward its road line; the keyring lies beyond the fold, its tag turned face down. A short length of thread joins them but does not reach the road.",anchor={map="EkronStashMap8",mark=1}},
{id="t0015-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The note that asks someone to come back",body="“Forget the box. Just get here before the rows are watered.” The lower half is torn away; a muddy thumb has blurred the place where a name would go.",anchor={map="EkronStashMap8",mark=1}},
-- T0016
{id="t0016-01",kind="set",pieces={"Map","KeyRing"},where={{place="transmission",spot="vehicle",lean="containment",rival="agricultural"}},title="The last stop crossed off the van route",body="The route on the map ends at a closed road. A keyring is tucked beneath the last stop, its tag stamped “return”; the return line has been crossed out.",anchor={scene="RVSPlonkies"}},
{id="t0016-02",kind="set",pieces={"SeedBag","Fertilizer"},where={{place="farm",spot="vehicle",lean="agricultural",rival="containment"}},title="The seed sack kept beside the fertilizer",body="The seed sack is wedged against the fertilizer bag in the van. Its stitched mouth is green at one corner; the label on the fertilizer is clean where a thumb would lift it.",anchor={scene="RVSPlonkies"}},
-- T0017
{id="t0017-01",kind="set",pieces={"FirstAidKit","Bandage"},where={{place="police",spot="furniture",lean="containment",rival="agricultural"}},title="The first-aid kit under the kitchen shelf",body="The kit is sealed and pushed behind a rat-chewed board. One bandage has been set on top, dry and neatly folded as if someone expected to return for it.",anchor={scene="RDSRatKing"}},
{id="t0017-02",kind="set",pieces={"GardeningSprayEmpty","Notebook"},where={{place="farm",spot="furniture",lean="agricultural",rival="containment"}},title="The spray bottle with a page stuck to it",body="The empty sprayer is tacky around its trigger. A notebook page has dried against its side; the page shows a rat-chewed root beside three crop rows.",anchor={scene="RDSRatKing"}},
-- T0018
{id="t0018-01",kind="set",pieces={"Clipboard","KeyRing"},where={{place="office",spot="furniture",lean="containment",rival="agricultural"}},title="The studio key clipped to a blank rundown",body="The keyring is clipped to a blank page in the studio desk. The only pencilled line says “doors locked”; the box for who checked them is empty.",anchor={scene="RBJackieJaye",version="A"}},
{id="t0018-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="office",spot="furniture",lean="agricultural",rival="containment"}},title="The field sketch under the studio glass",body="The notebook is trapped beneath a glass desk cover. A crop-row sketch has a water stain across its center; the bottle beside it is dry and capped.",anchor={scene="RBJackieJaye",version="B"}},
-- T0020
{id="t0020-01",kind="set",pieces={"SheetPaper2","Pencil","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Road closure practice",body="Lesson dates stop at the county road closure; the house key is tied to the page beside a note to keep the fee for the missed lessons. No return date is written.",anchor={map="BBurgStashMap1",mark=1}},
{id="t0020-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Closed windows",body="Please keep the lesson room shut until the roadside spray test is over. The children can still hear the truck from the front room; their mother has paid for the whole week already.",anchor={map="BBurgStashMap1",mark=1}},
-- T0021
{id="t0021-01",kind="set",pieces={"Map","KeyRing","Pencil"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="No return time",body="The pencilled route to the house ends at an ammunition collection point; the key ring is tagged 'back before supper,' but no return time is entered.",anchor={map="LouisvilleStashMap1",mark=1}},
{id="t0021-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The tin is for screws",body="The test-plot sample jars lost their labels in the rain. Don't put pesticide samples in the rifle-cleaning tin again; the household still keeps its loose screws there.",anchor={map="LouisvilleStashMap1",mark=1}},
-- T0022
{id="t0022-01",kind="set",pieces={"ShotgunShells","Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Inventory closed before the gate",body="The shell box is signed out at 6:10, the marked route is closed at 5:40, and a spare key is still tied to the map. The return box is blank.",anchor={map="MarchRidgeStashMap1",mark=1}},
{id="t0022-02",kind="written",pieces={"notepad"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The jars stay sealed",body="Keep the pesticide trial jars sealed until the boundary check is done. The neighbor keeps knocking because the map says don't go; the dog is still in the yard.",anchor={map="MarchRidgeStashMap1",mark=1}},
-- T0023
{id="t0023-01",kind="set",pieces={"RadioReceiver","Battery","Screwdriver"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Acknowledged from the bench",body="The receiver sat on the repair bench during the evacuation alert, screwdriver beside its charged battery. Dispatch's log says it acknowledged the alert there. The owner signed for it next morning and lost lunch money for the missed shift.",anchor={print="CircuitalHealing"}},
{id="t0023-02",kind="written",pieces={"receipt"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="No fault at the plot",body="The field trial's receiver came back marked 'no fault found,' though it stopped transmitting at the plot. The owner asked to hold the invoice until after harvest; the bench still wants payment.",anchor={print="CircuitalHealing"}},
-- T0024
{id="t0024-01",kind="set",pieces={"SpeedingTicket","BeerBottle","Pencil"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="A citation after closing",body="The speeding citation is stamped after the access lane's closure; the beer at the gate is still sealed, and the appeal line says its driver was taking a child home.",anchor={print="IrvingtonSpeedway"}},
{id="t0024-02",kind="written",pieces={"memo"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The infield stays closed",body="Keep the infield closed until the pesticide trial dries. The first heat remains on the board, so the groundskeeper has to refund a child's ticket from his own coffee jar.",anchor={print="IrvingtonSpeedway"}},
-- T0027
{id="t0027-01",kind="set",pieces={"SheetPaper2","Pencil","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The key return",body="A master key lies across a folded departure notice; the hall door was logged locked before the bus left, though a margin says it stood open. The custodian has underlined “return key” twice.",anchor={map="BBurgStashMap2",mark=1}},
{id="t0027-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Before the beds dry",body="The caretaker says the grounds crew borrowed the kitchen sink for a rinse. Please keep the side room locked until the treated beds are dry; the folding chairs are still needed tomorrow.",anchor={map="BBurgStashMap2",mark=1}},
-- T0028
{id="t0028-01",kind="set",pieces={"EmptyJar","Pencil","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The unfinished handoff",body="The kitchen jar sits beside a rinse note for the grounds crew; the fish order was cancelled on the same afternoon.",anchor={map="BBurgStashMap3",mark=1}},
{id="t0028-02",kind="written",pieces={"receipt"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Kept from the drawer",body="The repair ticket orders the front doors open for pickup, but the locksmith billed for cutting off the back lock. Tomorrow’s lunch count is still pencilled in.",anchor={map="BBurgStashMap3",mark=1}},
-- T0029
{id="t0029-01",kind="set",pieces={"SheetPaper2","Pencil","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The unfinished handoff",body="The pickup card assigns each trailer a time, then records the vehicle at the gate before the first family is listed. The spare hitch key is still here.",anchor={map="BBurgStashMap4",mark=1}},
{id="t0029-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Kept from the drawer",body="You said one bite was enough, so I marked the water barrel too. The field crew calls the rinse routine; I still will not let the dog drink until the tank is flushed.",anchor={map="BBurgStashMap4",mark=1}},
-- T0030
{id="t0030-01",kind="written",pieces={"receipt"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The unfinished handoff",body="Do not sell the catch until the county finishes its water check. They called it routine, but the fish order is still in the icebox and the supplier wants payment.",anchor={map="BBurgStashMap5",mark=1}},
{id="t0030-02",kind="set",pieces={"TinOpener","SheetPaper2","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Kept from the drawer",body="The cold-room key is tied to a delivery slip marked received before the road closure. The sealed box is still listed as waiting at the storage units.",anchor={map="BBurgStashMap5",mark=1}},
-- T0031
{id="t0031-01",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The unfinished handoff",body="I left the spare key where you asked. The bus went past the property, but the office says our address was never on its pickup list. I thought you would come back for me.",anchor={map="BBurgStashMap6",mark=1}},
{id="t0031-02",kind="set",pieces={"Notebook","Pencil","Teacup"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Kept from the drawer",body="Two cups are set beside a test-day notebook. The only signed line is for the room key; a note asks that the sample page stay out of the household drawer.",anchor={map="BBurgStashMap6",mark=1}},
-- T0032
{id="t0032-01",kind="set",pieces={"BaseballBat","KeyRing","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The unfinished handoff",body="The gate key is pinned under a closure notice dated after the guard shift ended. Someone wedged a bat across the latch from the inside.",anchor={map="BBurgStashMap7",mark=1}},
{id="t0032-02",kind="written",pieces={"notepad"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Kept from the drawer",body="Leave the canisters outside the fence until the grounds crew finishes the test. The gate was already locked when the delivery arrived; the return form charges us for the missing seal.",anchor={map="BBurgStashMap7",mark=1}},
-- T0033
{id="t0033-01",kind="set",pieces={"Notebook","KeyRing","WaterBottle"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The unfinished handoff",body="Two keys are taped to separate collection times. A bottle marked for the passenger has no return mark, though the driver’s sheet says every seat was cleared.",anchor={map="BBurgStashMap8",mark=1}},
{id="t0033-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Kept from the drawer",body="The room smells like the liquid from the field bottles, and Mom’s throat still hurts. I opened the window; the return truck says nothing spilled.",anchor={map="BBurgStashMap8",mark=1}},
-- T0034
{id="t0034-01",kind="set",pieces={"Screwdriver","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Tool return",body="The factory tool sheet lists the sprayer nozzle as returned before the shift began; a grease thumbprint covers the signature.",anchor={map="EkronStashMap1",mark=1}},
-- T0035
{id="t0035-01",kind="set",pieces={"Potato","Notebook"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The last crate",body="The vegetable crate has a delivery tag dated after the road was closed. A pencilled note asks whether the driver should still be charged for the trip.",anchor={map="EkronStashMap2",mark=1}},
-- T0036
{id="t0036-01",kind="set",pieces={"Bag_ALICEpack","Fertilizer"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Goods kept apart",body="A fertilizer bag is tied shut inside a supply pack; the page tucked under it lists a return trip but no recipient.",anchor={map="EkronStashMap3",mark=1}},
-- T0037
{id="t0037-01",kind="set",pieces={"KeyRing","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Empty address line",body="The spare key is tagged for the address but the transfer sheet has no receiving signature. Someone has checked the box marked “delivered.”",anchor={map="EkronStashMap4",mark=1}},
-- T0038
{id="t0038-01",kind="set",pieces={"Bandage","Notebook"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Aid for the school",body="The school aid list pairs a bandage with a note to keep the test-room door shut; the last line asks who will collect the used kit.",anchor={map="EkronStashMap5",mark=1}},
-- T0039
{id="t0039-01",kind="set",pieces={"Bleach","WaterBottle"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Advice by the sink",body="A bottle of bleach sits beside a copied warning and a water bottle with its cap still sealed. The note says the caller was told to wait for instructions.",anchor={map="EkronStashMap6",mark=1}},
-- T0040
{id="t0040-01",kind="set",pieces={"Map","Pencil"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="A route left open",body="The marked route has a pencilled return arrow but no destination name; a note beside it asks whether the field check is still happening.",anchor={map="EkronStashMap7",mark=1}},
-- T0041
{id="t0041-01",kind="set",pieces={"LetterHandwritten","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The threat with a key",body="A house key is wrapped in a threatening note; the envelope has a return mark but no delivery mark.",anchor={map="IrvingtonStashMap2",mark=1}},
-- T0042
{id="t0042-01",kind="set",pieces={"WalkieTalkie1","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Radio at the school",body="The school route slip tells the driver to radio before turning back; its attendance copy lists the field crew under “visitors.”",anchor={map="IrvingtonStashMap3",mark=1}},
-- T0043
{id="t0043-01",kind="set",pieces={"SheetPaper2","Pencil"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="A verse on the return",body="A copied verse about helping a wounded stranger is folded around an unpaid bar tab; the return slip marks the road pass as revoked.",anchor={map="IrvingtonStashMap4",mark=1}},
-- T0044
{id="t0044-01",kind="set",pieces={"Potato","KeyRing"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Food left for later",body="A food bag is tied to the pantry key with a note to leave one portion for the next shift. The kitchen list says the garden delivery never arrived.",anchor={map="IrvingtonStashMap5",mark=1}},
-- T0045
{id="t0045-01",kind="set",pieces={"HandTorch","Map"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Light for the careful",body="The torch is set on a marked route beside a note to check each door before leaving. The last checked address has no time beside it.",anchor={map="IrvingtonStashMap6",mark=1}},
-- T0046
{id="t0046-01",kind="set",pieces={"Notebook","SeedBag"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Field notes without a heading",body="A seed packet rests in a notebook whose first page is missing; the only surviving line asks whether the plots were watered before the crew arrived.",anchor={map="IrvingtonStashMap7",mark=1}},
-- T0047
{id="t0047-01",kind="set",pieces={"BathTowel","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The last clean towel",body="A laundry token is tied to the restaurant key, but the posted pickup list ends before the names marked “still here.”",anchor={map="IrvingtonStashMap8",mark=1}},
-- T0048
{id="t0048-01",kind="set",pieces={"Hammer","Nails"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Fortification order",body="A hammer and unopened nails sit beside a note to brace the garden-side door before the next treatment. The note does not say who will return.",anchor={map="IrvingtonStashMap9",mark=1}},
-- T0049
{id="t0049-01",kind="set",pieces={"RadioBlack","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="We will stay reachable",body="A radio is packed with the house key and a note promising someone will remain at the marked address. The battery receipt is dated after the promised check-in.",anchor={map="IrvingtonStashMap10",mark=1}},
-- T0050
{id="t0050-01",kind="set",pieces={"Book","LetterHandwritten"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="A gift for the visit",body="A book is wrapped in a note asking someone to bring it on a family visit; the back mentions keeping the garden hose off the marked ground.",anchor={map="LouisvilleStashMap2",mark=1}},
-- T0051
{id="t0051-01",kind="set",pieces={"Screwdriver","Notebook"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Tools left at school",body="The janitor’s tool list marks the rear door repaired, but the key return is dated before the repair was finished.",anchor={map="LouisvilleStashMap3",mark=1}},
-- T0052
{id="t0052-01",kind="set",pieces={"Sledgehammer","PetrolCan"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The stop at the station",body="A sledge is marked for a station delivery while the fuel can is logged as empty before the driver’s return. The receipt leaves the destination blank.",anchor={map="LouisvilleStashMap4",mark=1}},
-- T0053
{id="t0053-01",kind="set",pieces={"Bag_Schoolbag","WaterBottle"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="A family moved on",body="A school bag and water bottle are listed for collection at the gym, but the driver marked the family transferred before the pickup time.",anchor={map="LouisvilleStashMap5",mark=1}},
-- T0054
{id="t0054-01",kind="set",pieces={"SeedBag","WaterBottle"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Home plot notes",body="A seed bag is stored beside a water bottle labelled for the back plot; a note says to stop watering until the test results arrive.",anchor={map="LouisvilleStashMap6",mark=1}},
-- T0055
{id="t0055-01",kind="set",pieces={"KeyRing","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Everything accounted for",body="The house key is clipped to a checklist that says the rooms were cleared; a note on the reverse asks who will collect the owner’s coat.",anchor={map="LouisvilleStashMap7",mark=1}},
-- T0056
{id="t0056-01",kind="set",pieces={"Pills","Notebook"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Third door supply",body="A packet of pills is paired with a note to keep the third room ventilated after the bottles are opened. The return line for the bottles is blank.",anchor={map="LouisvilleStashMap8",mark=1}},
-- T0057
{id="t0057-01",kind="set",pieces={"HuntingRifle","CannedCorn"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Stable stores",body="A food tin is tied to a stable key with a route note warning the next driver not to take the tree road. The return time is crossed out.",anchor={map="LouisvilleStashMap9",mark=1}},
-- T0058
{id="t0058-01",kind="set",pieces={"Bread","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Food without a gun",body="A bread receipt is tucked inside a note asking the next visitor not to bring a crowd. The back lists a garden delivery that never reached the house.",anchor={map="LouisvilleStashMap10",mark=1}},
-- T0059
{id="t0059-01",kind="set",pieces={"KeyRing","Notebook"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Storage access list",body="The storage key is attached to a list that marks the units empty, although a handwritten note asks for another count before the hospital run.",anchor={map="LouisvilleStashMap11",mark=1}},
-- T0060
{id="t0060-01",kind="set",pieces={"Pizza","WaterBottle"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Food tent supply",body="The tent’s drink list includes water from the garden hose; a note says the hose was used to rinse equipment before the food shift.",anchor={map="LouisvilleStashMap12",mark=1}},
-- T0061
{id="t0061-01",kind="set",pieces={"Hammer","Garbagebag"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Backyard clearing list",body="The house list calls the yards secure, but a tied garbage bag contains the last gate latch and a note to check behind each fence.",anchor={map="LouisvilleStashMap13",mark=1}},
-- T0062
{id="t0062-01",kind="set",pieces={"Nails","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Half-hour repair",body="The plank receipt is stapled to a note asking everyone to stay outside until the treated boards dry. A radio call time is written beside “half hour.”",anchor={map="LouisvilleStashMap14",mark=1}},
-- T0063
{id="t0063-01",kind="set",pieces={"Book","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The gallery key",body="The gallery key is wrapped in a request to protect the collection; the handover form says the building was secure before the key was returned.",anchor={map="LouisvilleStashMap15",mark=1}},
-- T0064
{id="t0064-01",kind="set",pieces={"Bag_Schoolbag","Map"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Safe route south",body="A child’s bag is packed with a route note directing the family south; the same page warns them away from the treated street.",anchor={map="LouisvilleStashMap16",mark=1}},
-- T0065
{id="t0065-01",kind="set",pieces={"Pistol","SheetPaper2"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Supplies at the store",body="A pistol is wrapped in a store receipt with a note to leave the remaining supplies for the next family. The collection time is earlier than the closure notice.",anchor={map="MarchRidgeStashMap2",mark=1}},
-- T0066
{id="t0066-01",kind="set",pieces={"Bread","Map"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Last place on the route",body="A bakery receipt is tucked into a hunting route map; a note marks the last sighting beside a field-use date that was crossed out.",anchor={map="MarchRidgeStashMap3",mark=1}},
}}
