-- DERIVED FILE - do not edit by hand. The No Help clue list (Manifest.clues).
--   lua5.1 tools/nohelp_content/convert.lua
-- from content/nohelp/accepted/*.json; authoring fields live in the sidecars
-- (content/nohelp/accepted/sidecar/). Writer and engineer material: the owner
-- plays blind and does not read this file.
return {clues={
-- T0001
{id="t0001-01",kind="set",pieces={"Map","KeyRing"},where={{place="police",spot="mailbox",lean="containment",rival="agricultural"}},title="The route stops at the barrier",body="The map's pencil road ends at a barrier mark. A keyring is tied across the fold; its blank tag is polished where a number was rubbed away."},
{id="t0001-02",kind="set",pieces={"Bucket","WaterBottle"},where={{place="police",spot="mailbox",lean="agricultural",rival="containment"}},title="The bottle kept the wrong color",body="A green ring stains the bottle's inner neck. The bucket beside it is dry, though its handle is wet and smells faintly of crushed leaves."},
-- T0002
{id="t0002-01",kind="set",pieces={"FirstAidKit","Bandage"},where={{place="hospital",spot="corpse",lean="containment",rival="agricultural",outfit="medical"}},title="The sealed kit on the medical coat",body="The kit's seal is unbroken. A bandage has been folded around its handle, still clean, with a patient wrist label tied through the fold and no name on it."},
{id="t0002-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="hospital",spot="corpse",lean="agricultural",rival="containment",outfit="medical"}},title="The bottle with a leaf-shaped tide",body="A brown tide line circles the bottle; the notebook beside it has one page stuck to the cap. When it lifts, a pressed leaf outline remains on the paper."},
-- T0003
{id="t0003-01",kind="set",pieces={"Map","KeyRing"},where={{place="farm",spot="ground",lean="containment",rival="agricultural"}},title="The key past the closure bar",body="The map shows a farm track ending at a thick road-closure bar. The keyring lies beyond it, tied to a tag stamped “county return.” Beside the bar, “all clear” is checked although the road is still crossed out."},
{id="t0003-02",kind="set",pieces={"SeedBag","HandShovel"},where={{place="farm",spot="ground",lean="agricultural",rival="containment"}},title="The seed bag holds a narrow trench",body="The seed bag is folded shut around the shovel handle. A straight line of dark soil runs from the blade to the bag's seam, but the shovel has no soil on its grip."},
-- T0004
{id="t0004-01",kind="set",pieces={"Map","Lunchbox"},where={{place="checkpoint",spot="vehicle",lean="containment",rival="agricultural"}},title="The lunch packed for the closed lane",body="The lunchbox is wedged beneath the map's fold. The route line passes the checkpoint and stops; a spoon has been laid across the road home."},
{id="t0004-02",kind="set",pieces={"Bucket","Fertilizer"},where={{place="checkpoint",spot="vehicle",lean="agricultural",rival="containment"}},title="The powder gathered in the bucket seam",body="Pale granules cling inside the bucket's rim. The fertilizer sack beside it is dry and carefully folded, with its open corner tucked under the seat."},
-- T0005
{id="t0005-01",kind="set",pieces={"Briefcase","Screwdriver"},where={{place="office",spot="furniture",lean="containment",rival="agricultural"}},title="The briefcase with an intact lock",body="The screwdriver lies inside the open briefcase. Its lock is intact, but the metal around the keyhole is bright from repeated turning; a loose key sits in the lining."},
{id="t0005-02",kind="set",pieces={"SeedBag","Fertilizer"},where={{place="office",spot="furniture",lean="agricultural",rival="containment"}},title="The seed packet tucked in the fertilizer fold",body="A seed packet is tucked into the fertilizer sack's stitched fold. Its planting diagram is intact; the small panel for mixing instructions has been cut out cleanly."},
-- T0006
{id="t0006-01",kind="set",pieces={"Map","Postcard"},where={{place="bookstore",spot="mailbox",lean="containment",rival="agricultural"}},title="The postcard addressed to a crossed street",body="The postcard is stamped and addressed, but the map beneath it ends at a street crossed out in pencil. The message stops after, “We were told to wait by—”."},
{id="t0006-02",kind="set",pieces={"Newspaper","Notebook"},where={{place="bookstore",spot="mailbox",lean="agricultural",rival="containment"}},title="The garden column with no matching season",body="A newspaper gardening column is folded around a notebook sketch of three crop rows. The drawing has a water line but no planting date; the column is for winter."},
-- T0007
{id="t0007-01",kind="set",pieces={"Clipboard","KeyRing"},where={{place="transmission",spot="vehicle",lean="containment",rival="agricultural"}},title="The keyring clipped over the empty page",body="The clipboard is closed around a keyring. One key leaves a clean outline in the dust, while the page beneath the clip has torn away at the holes."},
{id="t0007-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="transmission",spot="vehicle",lean="agricultural",rival="containment"}},title="The rain sketch runs into the bottle ring",body="The notebook shows rain crossing a set of crop rows. A water bottle rests on the open page; its dry ring circles the word “downhill,” written once and then erased."},
-- T0008
{id="t0008-01",kind="set",pieces={"Lunchbox","KeyRing"},where={{place="warehouse",spot="ground",lean="containment",rival="agricultural"}},title="The keys stayed outside the marked floor",body="The keyring is wrapped in the lunchbox's cloth lining. A chalk boundary crosses the lid; the ring is on the clean side and the meal on the dusty one."},
{id="t0008-02",kind="set",pieces={"Bucket","Notebook"},where={{place="warehouse",spot="ground",lean="agricultural",rival="containment"}},title="The trial strip curled after spraying",body="The notebook rests across the bucket. Its page labels two strips “control — standing” and “trial spray — curled by noon.” The next line reads “mix still active after valve shut.”"},
-- T0009
{id="t0009-01",kind="set",pieces={"Newspaper","RubberBand"},where={{place="government",spot="furniture",lean="containment",rival="agricultural"}},title="The headline held open over its correction",body="A rubber band keeps the newspaper open, but its fold covers the correction column. The headline is still visible; the folded page has split along the correction's first sentence."},
{id="t0009-02",kind="set",pieces={"GardeningSprayEmpty","Notebook"},where={{place="government",spot="furniture",lean="agricultural",rival="containment"}},title="The sprayer left its outline on the page",body="The empty garden sprayer has left a clean circle on the notebook beneath it. A dried green line runs from the nozzle to a sketch of crop rows."},
-- T0010
{id="t0010-01",kind="written",pieces={"idcard"},where={{place="farm",spot="corpse",lean="agricultural",rival="containment",outfit="farm"}},person="person-a",title="Temporary field access card",body="Field plots: weekly soil checks. Road access may close at short notice. Reverse: “Keep the old mare in the dry stall tonight.”"},
{id="t0010-02",kind="set",pieces={"Map","HandShovel"},where={{place="farm",spot="corpse",lean="agricultural",rival="containment",outfit="farm"}},person="person-a",title="The row that ends at the road",body="The map's crop row reaches the road and stops at a thumb-smudged mark. Soil fills the shovel socket but not the blade; its grip is clean."},
-- T0011
{id="t0011-01",kind="written",pieces={"idcard"},where={{place="office",spot="mailbox",lean="containment",rival="agricultural"}},person="person-b",title="County message runner card",body="Delivery: office to road crews. Return copy expected when access resumes. Reverse: “Please bring the chipped blue cup back; it was my sister's.”"},
{id="t0011-02",kind="set",pieces={"Clipboard","KeyRing"},where={{place="office",spot="mailbox",lean="containment",rival="agricultural"}},person="person-b",title="The clipboard held the only spare",body="A keyring is fastened beneath the clipboard clip. Its tag is worn smooth; the page above it has two pencil holes and no writing."},
-- T0012
{id="t0012-01",kind="written",pieces={"businesscard"},where={{place="checkpoint",spot="vehicle",lean="containment",rival="agricultural"}},person="person-c",title="Courier card with a late return",body="Transfer window: after road access ends. Return copy to sender. Reverse: “Bread for Mother, no crust if it is still warm.”"},
{id="t0012-02",kind="set",pieces={"Map","KeyRing"},where={{place="checkpoint",spot="vehicle",lean="agricultural",rival="containment"}},person="person-c",title="The key marked for the last spray run",body="The map routes past a checkpoint to the trial plots. A key tag says “sprayer pump.” In the margin, “wind turned at ten; east beans scorched by noon” is underlined twice."},
-- T0013
{id="t0013-01",kind="set",pieces={"Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The lap with no return mark",body="The map's route ends at a chalk line. A keyring rests across the fold back toward the starting point; its tag has no place name.",anchor={map="IrvingtonStashMap1",mark=1}},
{id="t0013-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The bottle's ring crosses a row sketch",body="A clear ring dries across the notebook's crop-row drawing. The bottle cap is clean; the page beneath it is stained only where the drawn rows meet.",anchor={map="IrvingtonStashMap1",note=1}},
{id="t0013-03",kind="written",pieces={"dispatch"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Dispatch copy with an unfinished return",body="“Track access ends at the barrier. Keep the west lane clear for the last vehicle.” The receiving line is blank; on the back, someone asks for a green scarf to be saved.",anchor={map="IrvingtonStashMap1",note=2}},
{id="t0013-04",kind="written",pieces={"notepad"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The row count continues past the page",body="The note lists three crop rows and a water check, then continues onto the cover. “Bring the small boots home” is written below the last line.",anchor={map="IrvingtonStashMap1",note=3}},
-- T0014
{id="t0014-01",kind="set",pieces={"Screwdriver","RubberBand"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The tire offer marked on a tool handle",body="A rubber band holds a service slip to the screwdriver. Four circles are drawn beside one wheel sketch; only the outer groove is filled with dark dust.",anchor={print="AmericanTire"}},
{id="t0014-02",kind="written",pieces={"receipt"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The fourth tire omitted from the return",body="The receipt charges four tires to the county road crew, but lists only three serial numbers. Beside the blank fourth line, someone wrote “keep off public return until clearance review.” Reverse: “Save the smoothest for the child's bicycle.”",anchor={print="AmericanTire"}},
-- T0015
{id="t0015-01",kind="set",pieces={"Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="The key points past the marked road",body="The map is folded toward its road line; the keyring lies beyond the fold, its tag turned face down. A short length of thread joins them but does not reach the road.",anchor={map="EkronStashMap8",mark=1}},
{id="t0015-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The note that asks someone to come back",body="“Forget the box. Just get here before the rows are watered.” The lower half is torn away; a muddy thumb has blurred the place where a name would go.",anchor={map="EkronStashMap8",mark=1}},
-- T0016
{id="t0016-01",kind="set",pieces={"Map","KeyRing"},where={{place="transmission",spot="vehicle",lean="containment",rival="agricultural"}},title="The last stop crossed off the van route",body="The route on the map ends at a closed road. A keyring is tucked beneath the last stop, its tag stamped “return”; the return line has been crossed out.",anchor={scene="RVSPlonkies"}},
{id="t0016-02",kind="set",pieces={"SeedBag","Fertilizer"},where={{place="farm",spot="vehicle",lean="agricultural",rival="containment"}},title="The seed sack kept beside the fertilizer",body="The seed sack is wedged against the fertilizer bag in the van. Its stitched mouth is green at one corner; the label on the fertilizer is clean where a thumb would lift it.",anchor={scene="RVSPlonkies"}},
-- T0017
{id="t0017-01",kind="set",pieces={"FirstAidKit","Bandage"},where={{place="police",spot="furniture",lean="containment",rival="agricultural"}},title="The first-aid kit under the kitchen shelf",body="The kit is sealed and pushed behind a rat-chewed board. One bandage has been set on top, dry and neatly folded as if someone expected to return for it.",anchor={scene="RDSRatKing"}},
{id="t0017-02",kind="set",pieces={"GardeningSprayEmpty","Notebook"},where={{place="farm",spot="furniture",lean="agricultural",rival="containment"}},title="The spray bottle with a page stuck to it",body="The empty sprayer is tacky around its trigger. A notebook page has dried against its side; the page shows a rat-chewed root beside three crop rows.",anchor={scene="RDSRatKing"}},
-- T0018
{id="t0018-01",kind="set",pieces={"Clipboard","KeyRing"},where={{place="office",spot="furniture",lean="containment",rival="agricultural"}},title="The studio key clipped to a blank rundown",body="The keyring is clipped to a blank page in the studio desk. The only pencilled line says “doors locked”; the box for who checked them is empty.",anchor={scene="RBJackieJaye",version="A"}},
{id="t0018-02",kind="set",pieces={"Notebook","WaterBottle"},where={{place="office",spot="furniture",lean="agricultural",rival="containment"}},title="The field sketch under the studio glass",body="The notebook is trapped beneath a glass desk cover. A crop-row sketch has a water stain across its center; the bottle beside it is dry and capped.",anchor={scene="RBJackieJaye",version="B"}},
-- T0020
{id="t0020-01",kind="set",pieces={"SheetPaper2","Pencil","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Road closure practice",body="Lesson dates stop at the county road closure; the house key is tied to the page beside a note to keep the fee for the missed lessons. No return date is written.",anchor={map="BBurgStashMap1",mark=1}},
{id="t0020-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="Closed windows",body="Please keep the lesson room shut until the roadside spray test is over. The children can still hear the truck from the front room; their mother has paid for the whole week already.",anchor={map="BBurgStashMap1",mark=1}},
-- T0021
{id="t0021-01",kind="set",pieces={"Map","KeyRing","Pencil"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="No return time",body="The pencilled route to the house ends at an ammunition collection point; the key ring is tagged 'back before supper,' but no return time is entered.",anchor={map="LouisvilleStashMap1",mark=1}},
{id="t0021-02",kind="written",pieces={"letter"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The tin is for screws",body="The test-plot sample jars lost their labels in the rain. Don't put pesticide samples in the rifle-cleaning tin again; the household still keeps its loose screws there.",anchor={map="LouisvilleStashMap1",mark=1}},
-- T0022
{id="t0022-01",kind="set",pieces={"ShotgunShells","Map","KeyRing"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="Inventory closed before the gate",body="The shell box is signed out at 6:10, the marked route is closed at 5:40, and a spare key is still tied to the map. The return box is blank.",anchor={map="MarchRidgeStashMap1",mark=1}},
{id="t0022-02",kind="written",pieces={"notepad"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The jars stay sealed",body="Keep the pesticide trial jars sealed until the boundary check is done. The neighbor keeps knocking because the map says don't go; the dog is still in the yard.",anchor={map="MarchRidgeStashMap1",mark=1}},
-- T0024
{id="t0024-01",kind="set",pieces={"SpeedingTicket","BeerBottle","Pencil"},where={{place="mapNamed",spot="ground",lean="containment",rival="agricultural"}},title="A citation after closing",body="The speeding citation is stamped after the access lane's closure; the beer at the gate is still sealed, and the appeal line says its driver was taking a child home.",anchor={print="IrvingtonSpeedway"}},
{id="t0024-02",kind="written",pieces={"memo"},where={{place="mapNamed",spot="ground",lean="agricultural",rival="containment"}},title="The infield stays closed",body="Keep the infield closed until the pesticide trial dries. The first heat remains on the board, so the groundskeeper has to refund a child's ticket from his own coffee jar.",anchor={print="IrvingtonSpeedway"}},
}}
