#!/usr/bin/env python3
"""Turn the owner's drawing of the case into the mod's art and geometry.

    tools/build_organiser_case.py

The source of truth is art/organiser-case.png (with art/organiser-case.svg kept
beside it), drawn by the owner on 2026-09-12. This does two things and nothing
else: it scales the picture to the sizes the device is drawn at, and it writes
down where the glass and the keys are so the hit boxes sit on the art rather
than beside it.

Measurements are in the drawing's own pixels. The screen opening is found
automatically - it is a hole in the picture, and a hole is unambiguous. The
keys are measured by hand from the drawing, because they are raised mouldings
rather than holes and every automatic attempt read the shading between them as
an edge.
"""
from PIL import Image
from collections import deque
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "art/organiser-case.png")
OUT = os.path.join(REPO, "mod/common/media/ui/CFOrg")
LUA = os.path.join(REPO, "mod/common/media/lua/shared/ConspiracyFiles/Generated/OrganiserCase.lua")
SCALES = (1, 2, 3)

# Measured off the drawing at 3x magnification.
KEYS = [("MODE", 38, 372, 52, 32), ("PREV", 97, 372, 51, 32),
        ("NEXT", 155, 372, 52, 32), ("INDEX", 213, 372, 54, 32)]
LABELS = {"MODE": "FILES", "PREV": "NAMES", "NEXT": "DATES", "INDEX": "TO DO"}
POWER = (296, 300, 9, 26)     # the tab on the right edge
# No power light. Owner, 2026-09-12: "there is also no on off led. you can see
# on the screen if the device is on" - and a lamp drawn on a case that has none
# is a lie about the object.

def screen_hole(img):
    """The screen is the transparent region that the outside cannot reach."""
    w, h = img.size
    px = img.load()
    clear = lambda x, y: px[x, y][3] < 60
    seen = [[False] * w for _ in range(h)]
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if clear(x, y) and not seen[y][x]:
                seen[y][x] = True; q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if clear(x, y) and not seen[y][x]:
                seen[y][x] = True; q.append((x, y))
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and clear(nx, ny) and not seen[ny][nx]:
                seen[ny][nx] = True; q.append((nx, ny))
    # Rows of the hole, then the longest run of FULL-WIDTH rows. A drawing has
    # specks - a few stray transparent pixels near the keys - and taking the
    # bounding box of everything stretched the glass down over the bezel
    # (owner, 2026-09-12: "the glas goes to far down").
    rows = {}
    for y in range(h):
        xs = [x for x in range(w) if clear(x, y) and not seen[y][x]]
        if xs:
            rows[y] = (min(xs), max(xs), len(xs))
    if not rows:
        raise SystemExit("no screen opening found in the drawing")
    widest = max(r[2] for r in rows.values())
    best = run = None
    for y in sorted(rows):
        if rows[y][2] >= widest * 0.98:
            run = run or [y, y]
            run[1] = y
        elif run:
            if not best or run[1] - run[0] > best[1] - best[0]:
                best = run
            run = None
    if run and (not best or run[1] - run[0] > best[1] - best[0]):
        best = run
    top, bottom = best
    x0 = min(rows[y][0] for y in range(top, bottom + 1))
    x1 = max(rows[y][1] for y in range(top, bottom + 1))
    return x0, top, x1 - x0 + 1, bottom - top + 1

def main():
    art = Image.open(SRC).convert("RGBA")
    W, H = art.size
    gx, gy, gw, gh = screen_hole(art)
    os.makedirs(OUT, exist_ok=True)
    # The glass is a hole, so fill it: the shell must not be see-through.
    filled = art.copy()
    Image.Image.paste(filled, Image.new("RGBA", (gw, gh), (168, 178, 150, 255)), (gx, gy))
    for scale in SCALES:
        filled.resize((W * scale, H * scale), Image.LANCZOS).save(
            os.path.join(OUT, "case_%dx.png" % scale))
        # A pressed key: the same shape, darkened, drawn over the art.
        for name, (kx, ky, kw, kh) in [(n, (a, b, c, d)) for n, a, b, c, d in KEYS][:1]:
            key = Image.new("RGBA", (kw * scale, kh * scale), (26, 26, 28, 150))
            key.save(os.path.join(OUT, "press_%dx.png" % scale))
        Image.new("RGBA", (POWER[2] * scale, POWER[3] * scale), (26, 26, 28, 150)).save(
            os.path.join(OUT, "power_%dx.png" % scale))
        Image.new("RGBA", (POWER[2] * scale, POWER[3] * scale), (26, 26, 28, 150)).save(
            os.path.join(OUT, "rocker_%dx.png" % scale))
    with open(LUA, "w") as f:
        f.write("-- GENERATED by tools/build_organiser_case.py from art/organiser-case.png.\n")
        f.write("-- Do not edit by hand; redraw the art and run the tool.\n--\n")
        f.write("-- The owner's own drawing of the machine (2026-09-12). The screen opening\n")
        f.write("-- is found in the picture; the keys are measured from it.\n")
        f.write("local M={w=%d,h=%d,scales={1,2,3}}\n" % (W, H))
        f.write("M.glass={x=%d,y=%d,w=%d,h=%d}\n" % (gx, gy, gw, gh))
        f.write("M.buttons={\n")
        for name, x, y, w, h in KEYS:
            f.write(' {id="%s",x=%d,y=%d,w=%d,h=%d,round=true},\n' % (name, x, y, w, h))
        f.write(' {id="POWER",x=%d,y=%d,w=%d,h=%d},\n' % POWER)
        f.write("}\n")
        f.write("return M\n")
    print("case %dx%d, glass %d,%d %dx%d, %d keys" % (W, H, gx, gy, gw, gh, len(KEYS)))

if __name__ == "__main__":
    main()
