#!/usr/bin/env python3
"""Render the Palm OS face into bitmap alphabets for the organiser screen.

    tools/build_palm_font.py

The game ships a fixed set of bitmap fonts and will not register one from a
mod, so the organiser draws its own letters from a picture of an alphabet.
This builds that picture, plus the metrics table the screen reads.

The face is "Palm OS" by Damien Guard (fontstruct.com/fontstructions/show/653622),
CC BY-SA 3.0. It is drawn on a pixel grid, so it is rendered ONCE at its native
size and then enlarged by whole numbers with nearest-neighbour: every pixel stays
a square. Rendering at a larger point size instead would re-hint the outlines and
soften them.

Outputs (all generated, all committed):
    mod/common/media/ui/Organiser_Font_1x.png   native, 11px line
    mod/common/media/ui/Organiser_Font_2x.png
    mod/common/media/ui/Organiser_Font_3x.png
    mod/common/media/lua/shared/ConspiracyFiles/Generated/OrganiserFont.lua
"""
from PIL import Image, ImageDraw, ImageFont
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FONT = os.path.join(REPO, "mod/common/media/fonts/palm-os.otf")
UI = os.path.join(REPO, "mod/common/media/ui")
LUA = os.path.join(REPO, "mod/common/media/lua/shared/ConspiracyFiles/Generated/OrganiserFont.lua")
SIZE = 16          # the point size at which this face lands exactly on its grid
PAD = 4            # drawing margin while measuring a single glyph
FIRST, LAST = 32, 126
SCALES = (1, 2, 3)

def main():
    font = ImageFont.truetype(FONT, SIZE)
    ascent, descent = font.getmetrics()
    line = ascent + descent
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        cell = Image.new("L", (advance + PAD * 2, line + PAD * 2), 0)
        ImageDraw.Draw(cell).text((PAD, PAD), ch, font=font, fill=255)
        # Hard threshold: a pixel font has no grey, and any that appears is a
        # rendering artefact that would blur when enlarged.
        cell = cell.point(lambda v: 255 if v > 127 else 0)
        strip = cell.crop((PAD, PAD, PAD + advance, PAD + line))
        glyphs.append((code, advance, strip))

    width = sum(g[1] for g in glyphs)
    sheet = Image.new("RGBA", (width, line), (0, 0, 0, 0))
    x, table = 0, []
    for code, advance, strip in glyphs:
        mask = strip.convert("L")
        white = Image.new("RGBA", strip.size, (255, 255, 255, 255))
        sheet.paste(white, (x, 0), mask)
        table.append((code, x, advance))
        x += advance

    for scale in SCALES:
        out = sheet.resize((sheet.width * scale, sheet.height * scale), Image.NEAREST)
        out.save(os.path.join(UI, "Organiser_Font_%dx.png" % scale))

    with open(LUA, "w") as f:
        f.write("-- GENERATED by tools/build_palm_font.py. Do not edit by hand.\n")
        f.write("--\n")
        f.write("-- Metrics for the organiser screen's own alphabet, in NATIVE pixels;\n")
        f.write("-- the screen multiplies them by its whole-number scale. The face is\n")
        f.write('-- "Palm OS" by Damien Guard, CC BY-SA 3.0 - see media/fonts/license.txt.\n')
        f.write("local M={first=%d,last=%d,line=%d,ascent=%d,sheetWidth=%d}\n"
                % (FIRST, LAST, line, ascent, width))
        f.write("M.x={")
        f.write(",".join(str(x) for _, x, _ in table))
        f.write("}\n")
        f.write("M.w={")
        f.write(",".join(str(w) for _, _, w in table))
        f.write("}\n")
        f.write("return M\n")
    print("line height %d px, %d glyphs, sheet %d px wide" % (line, len(table), width))

if __name__ == "__main__":
    main()
