#!/usr/bin/env python3
"""Render the Palm OS face into the glyph pictures the organiser screen draws.

    tools/build_palm_font.py

TRIED FIRST, AND IT DOES NOT WORK: the game names its fonts in
media/fonts/<LANG>/fonts.txt, a mod may override that file, and the override IS
picked up - but the engine then loads the .fnt through its own file access,
which cannot see a mod's files, and the game dies on startup with
"FileNotFoundException: media/palmos.fnt" (2026-09-12). Registering a font from
a mod is not possible without patching the game's own install.

So the screen draws its own letters, one texture per glyph. A sheet is no good
either: Lua is given no way to draw part of a texture, so a sheet could only be
cut with a stencil per character - two extra state changes for every letter, on
a 2 ms frame budget.

The face is "Palm OS" by Damien Guard (CC BY-SA 3.0, see CREDITS.md). It is a
pixel font, so it is rendered once at its native size and enlarged by whole
numbers with nearest-neighbour - never re-rendered larger, which would soften
it.

WHY THESE FACES AND SCALES (P4-R99, owner, 2026-09-14). Machine size no longer
magnifies the text - it decides how much fits - so the glyphs needed are the
text sizes alone: the 16 pt face at 1x, 2x and 3x (11, 22 and 33 px), and the
same face re-rendered at 24 pt for a size between Small and Medium (17 px).
The owner saw both ways of getting that size and chose to keep Small and add
one; re-rendering keeps every stroke sharp, where stretching 1.5x does not.
The 4x, 6x and 9x sets only existed while text multiplied with machine size.
Nothing is ever drawn at a non-integer scale.

Outputs (generated, committed):
    mod/common/media/ui/CFOrg/<folder><scale>x/<code>.png   95 glyphs each
    mod/common/media/lua/shared/ConspiracyFiles/Generated/OrganiserFont.lua     16 pt
    mod/common/media/lua/shared/ConspiracyFiles/Generated/OrganiserFont24.lua   24 pt
"""
from PIL import Image, ImageDraw, ImageFont
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "mod/common/media/fonts/palm-os.otf")
UI = os.path.join(REPO, "mod/common/media/ui")
GENERATED = os.path.join(REPO, "mod/common/media/lua/shared/ConspiracyFiles/Generated")
FIRST, LAST = 32, 126
# (module, point size, folder prefix, scales). 16 pt is where this face lands
# exactly on its grid; 24 pt is its sharp in-between size.
FACES = (("OrganiserFont", 16, "", (1, 2, 3)),
         ("OrganiserFont24", 24, "b", (1,)))

def main():
    for module, size, prefix, scales in FACES:
        build(module, size, prefix, scales)

def build(module, SIZE, prefix, SCALES):
    LUA = os.path.join(GENERATED, module + ".lua")
    font = ImageFont.truetype(SRC, SIZE)
    ascent, descent = font.getmetrics()
    line = ascent + descent
    for scale in SCALES:
        folder = os.path.join(UI, "CFOrg", "%s%dx" % (prefix, scale))
        os.makedirs(folder, exist_ok=True)
        for name in os.listdir(folder):
            os.remove(os.path.join(folder, name))
    widths = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        widths.append(advance)
        if advance == 0:
            continue
        mask = Image.new("L", (advance, line), 0)
        ImageDraw.Draw(mask).text((0, 0), ch, font=font, fill=255)
        # A pixel font has no grey; any that appears is an artefact that would
        # blur once enlarged.
        mask = mask.point(lambda v: 255 if v > 127 else 0)
        cell = Image.new("RGBA", mask.size, (0, 0, 0, 0))
        cell.paste(Image.new("RGBA", mask.size, (255, 255, 255, 255)), (0, 0), mask)
        for scale in SCALES:
            out = cell.resize((cell.width * scale, cell.height * scale), Image.NEAREST)
            out.save(os.path.join(UI, "CFOrg", "%s%dx" % (prefix, scale), "%d.png" % code))

    with open(LUA, "w") as f:
        f.write("-- GENERATED by tools/build_palm_font.py. Do not edit by hand.\n--\n")
        f.write("-- The organiser screen draws its own letters: a mod cannot register a\n")
        f.write("-- font with the game (it crashes on startup - see the tool). Widths are\n")
        f.write("-- in NATIVE pixels, multiplied by the screen's scale; each glyph is a\n")
        f.write("-- texture at media/ui/CFOrg/<folder><scale>x/<code>.png.\n")
        f.write('-- Face: "Palm OS" by Damien Guard, CC BY-SA 3.0 - see CREDITS.md.\n')
        f.write("local M={first=%d,last=%d,line=%d,ascent=%d,size=%d,folder=%s,scales={%s}}\n" % (FIRST, LAST, line, ascent, SIZE, '"%s"' % prefix, ",".join(str(x) for x in SCALES)))
        f.write("M.w={%s}\n" % ",".join(str(w) for w in widths))
        f.write("""function M.width(text,scale)
 if type(text)~="string" then return 0 end
 local total=0
 for i=1,#text do
  local c=string.byte(text,i)
  if c>=M.first and c<=M.last then total=total+M.w[c-M.first+1] end
 end
 return total*(scale or 1)
end
return M
""")
    print("%s: %d pt, line %d px, %d glyphs, scales %s" % (module, SIZE, line, len(widths), SCALES))

if __name__ == "__main__":
    main()
